name: Build Project

on:
  # Using target instead of pull_request to allow dependabot to access secrets and pass to the shared workflow.
  pull_request_target:

jobs:
  build:
    uses: genesislcap/platform-releases/.github/workflows/product-gradle-pr-build.yaml@master
    with:
      repository: genesislcap/{{repoName}}
      branch-ref: ${{ github.event.pull_request.head.sha }}
      target-branch-ref: ${{ github.event.pull_request.base.ref }}
    secrets:
      JFROG_RO_USER : ${{ secrets.JFROG_RO_USER }}
      JFROG_RO_PASSWORD : ${{ secrets.JFROG_RO_PASSWORD }}
      SONAR_TOKEN : ${{ secrets.SONAR_TOKEN }}
      GPR_READ_TOKEN : ${{ secrets.GPR_READ_TOKEN }}